### ISSUE TITLE
Crashes in type in name and events???

### ISSUE THREAD

**Issue by nahboi** [BigNed/ToontownStride#1]
https://hastebin.com/paluceyeyu.sql

i played game for the first time 
and these crashes occured.

**Comment by EliasTDev** [comment]
Should be resolved. Please refer to these commits:
https://github.com/BigNed/ToontownStride/commit/ac7cf9da01a40050a0c7ed6974a3e76a25c56559
https://github.com/BigNed/ToontownStride/commit/f031e04319dc4a91e71b53a6b81982802f9baaa6

Thank you for reporting the crashes! They were simply a result of some engine upgrades and it happens that those errors were not caught.
